[project]
name = "taiwan_weather_mcp"
version = "0.1.0"
description = "Taiwan Weather MCP"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.5.0",
]
